/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class items extends javax.swing.JFrame {

    /**
     * Creates new form items
     */
    public items() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clips_pinsB = new javax.swing.JButton();
        eraserB = new javax.swing.JButton();
        pensB = new javax.swing.JButton();
        colorsB = new javax.swing.JButton();
        paperB = new javax.swing.JButton();
        extrasB = new javax.swing.JButton();
        stickersB = new javax.swing.JButton();
        booksB = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel4.setText("CraftTown Stationary!");

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Creation beyond Imagination :)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4))
                .addGap(124, 124, 124))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("List of Items Available");

        clips_pinsB.setBackground(new java.awt.Color(255, 255, 255));
        clips_pinsB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clips_pinsB.setForeground(new java.awt.Color(204, 0, 255));
        clips_pinsB.setText("Clips & Pins");
        clips_pinsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clips_pinsBActionPerformed(evt);
            }
        });

        eraserB.setBackground(new java.awt.Color(255, 255, 255));
        eraserB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eraserB.setForeground(new java.awt.Color(204, 0, 255));
        eraserB.setText("Eraser");
        eraserB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraserBActionPerformed(evt);
            }
        });

        pensB.setBackground(new java.awt.Color(255, 255, 255));
        pensB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pensB.setForeground(new java.awt.Color(204, 0, 255));
        pensB.setText("Pens");
        pensB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensBActionPerformed(evt);
            }
        });

        colorsB.setBackground(new java.awt.Color(255, 255, 255));
        colorsB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        colorsB.setForeground(new java.awt.Color(204, 0, 255));
        colorsB.setText("Colors");
        colorsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsBActionPerformed(evt);
            }
        });

        paperB.setBackground(new java.awt.Color(255, 255, 255));
        paperB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paperB.setForeground(new java.awt.Color(204, 0, 255));
        paperB.setText("Paper");
        paperB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperBActionPerformed(evt);
            }
        });

        extrasB.setBackground(new java.awt.Color(255, 255, 255));
        extrasB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        extrasB.setForeground(new java.awt.Color(204, 0, 255));
        extrasB.setText("Extras");
        extrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrasBActionPerformed(evt);
            }
        });

        stickersB.setBackground(new java.awt.Color(255, 255, 255));
        stickersB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stickersB.setForeground(new java.awt.Color(204, 0, 255));
        stickersB.setText("Stickers");
        stickersB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stickersBActionPerformed(evt);
            }
        });

        booksB.setBackground(new java.awt.Color(255, 255, 255));
        booksB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        booksB.setForeground(new java.awt.Color(204, 0, 255));
        booksB.setText("Books");
        booksB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksBActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(255, 0, 204));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clips_pinsB)
                                    .addComponent(eraserB)
                                    .addComponent(pensB)
                                    .addComponent(paperB))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extrasB)
                                    .addComponent(colorsB)
                                    .addComponent(booksB)
                                    .addComponent(stickersB)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paperB)
                    .addComponent(stickersB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clips_pinsB)
                    .addComponent(colorsB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eraserB)
                    .addComponent(booksB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pensB)
                    .addComponent(extrasB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paperBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperBActionPerformed
        // TODO add your handling code here:
        paper p = new paper();
        p.setVisible(true);
    }//GEN-LAST:event_paperBActionPerformed

    private void clips_pinsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clips_pinsBActionPerformed
        // TODO add your handling code here:
        clips_pins cp = new clips_pins();
        cp.setVisible(true);
    }//GEN-LAST:event_clips_pinsBActionPerformed

    private void eraserBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraserBActionPerformed
        // TODO add your handling code here:
        eraser e = new eraser();
        e.setVisible(true);
        
    }//GEN-LAST:event_eraserBActionPerformed

    private void pensBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensBActionPerformed
        // TODO add your handling code here:
        pen p = new pen();
        p.setVisible(true);
    }//GEN-LAST:event_pensBActionPerformed

    private void stickersBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stickersBActionPerformed
        // TODO add your handling code here:
        stickers s = new stickers();
        s.setVisible(true);
    }//GEN-LAST:event_stickersBActionPerformed

    private void colorsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsBActionPerformed
        // TODO add your handling code here:
        colors c =new colors();
        c.setVisible(true);
    }//GEN-LAST:event_colorsBActionPerformed

    private void booksBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksBActionPerformed
        // TODO add your handling code here:
        books b = new books();
        b.setVisible(true);
    }//GEN-LAST:event_booksBActionPerformed

    private void extrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrasBActionPerformed
        // TODO add your handling code here:
        extras e = new extras();
        e.setVisible(true);
        
    }//GEN-LAST:event_extrasBActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booksB;
    private javax.swing.JButton clips_pinsB;
    private javax.swing.JButton colorsB;
    private javax.swing.JButton eraserB;
    private javax.swing.JButton extrasB;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton paperB;
    private javax.swing.JButton pensB;
    private javax.swing.JButton stickersB;
    // End of variables declaration//GEN-END:variables
}
